name: Sync Upstream and Merge to ci-cd

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:      # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
      main_updated: ${{ steps.check_main_diff.outputs.main_updated }}
    steps:
      - name: Debug Secret
        run: |
          if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
            echo "❌ PAT_TOKEN is NOT set"
            exit 1
          else
            echo "✅ PAT_TOKEN is set"
          fi

      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
      - name: Fix git remote auth manually (fallback)
        run: |
          git remote set-url origin "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git"

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/hashicorp/terraform-mcp-server.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Checkout main and merge upstream
        run: |
          git checkout main
          git merge upstream/main --no-edit || true

      - name: Check if main has updates
        id: check_main_diff
        run: |
          git fetch origin main
          if git diff --quiet origin/main HEAD; then
            echo "main_updated=false" >> $GITHUB_OUTPUT
          else
            echo "main_updated=true" >> $GITHUB_OUTPUT
          fi

      - name: Push updated main
        if: steps.check_main_diff.outputs.main_updated == 'true'
        run: git push origin main

  merge_ci_cd:
    runs-on: ubuntu-latest
    needs: sync
    # if: needs.sync.outputs.main_updated == 'true'
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: EO-67998-create-ci-cd

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout EO-67998-create-ci-cd
        run: git checkout EO-67998-create-ci-cd

      - name: Merge main into EO-67998-create-ci-cd
        run: |
          git fetch origin main
          if git merge-base --is-ancestor origin/main HEAD; then
            echo "No new commits to merge from main"
          else
            git merge origin/main --no-edit || true
            git push origin EO-67998-create-ci-cd
          fi